config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'

  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def is_logged
      if !current_user
          redirect_to new_user_session_path
      end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_filter :is_logged

  def index
      @events = Event.where(:events => {user_id: current_user.id})
  end

  def new
  end

  def show
      @event = Event.find(params[:id])
      if not @event.user_id == current_user.id
          redirect_to root_path
      end
  end

  def create
      @event = Event.new(event_params)
      @event.user_id = current_user.id
      @event.completed = false
      @event.save
      redirect_to @event
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
      @event = Event.find(params[:id])
      @event.destroy
      redirect_to events_path
  end

  private
    def event_params
        params.require(:event).permit(
            :title,
            :description,
            :user_id,
            :place,
            :start_date,
            :end_date,
            :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/delete.html.erb
<h1>Events#delete</h1>
<p>Find me in app/views/events/delete.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div class="alert alert-dismissible alert-warning" id="myAlert">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4>Atención!</h4>
  <p>
      La base de datos ha sido reiniciada para una mejor implementación. Disculpa las molestias.
  </p>
</div>

<h1>Todos los eventos</h1>

<div>
    <table class="table table-stripped table-hover">
        <thead>
            <tr>
                <th>Completado</th>
                <th>Título</th>
                <th>Descripción</th>
                <th>Lugar</th>
                <th>Empieza</th>
                <th>Acaba</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <% @events.each do |event| %>
        <tr id="event-<%= event.id%>">
            <td><%= check_box_tag event.completed, class: "checkbox", id: event.id %></td>
            <td><strong><%= link_to event.title, event %><strong></td>
            <td><%= event.description %></td>
            <td><%= event.place %></td>
            <td><%= event.start_date %></td>
            <td><%= event.end_date %></td>
            <td><%= link_to 'X', event_path(event),
                    method: :delete,
                    data: { confirm: 'Estás seguro?' },
                    class: "btn btn-danger"%></td>
        </tr>
        <% end %>

    </table>
    <%if user_signed_in? %>
    <%= link_to 'Nuevo evento', new_event_path, class: "btn btn-primary" %>
    <% end %>

</div>

app/views/events/new.html.erb
<%= form_for Event.new , html:{class: "form-horizontal"} do |f| %>
<fieldset>
    <legend><h3>Nuevo evento</h3></legend>
    <div class="form-group">
        <label for="inputTitle" class="col-lg-2 control-label">Título</label>
        <div class="col-lg-10">
            <%= f.text_field :title,
            placeholder: "Título",
            id: "inputTitle",
            class: "form-control"
                %>
            </div>
        </div>
        <div class="form-group">
            <label for="inputPlace" class="col-lg-2 control-label">Lugar</label>
            <div class="col-lg-10">
                <%= f.text_field :place,
                placeholder: "Lugar",
                id: "inputPlace",
                class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
            <label for="textArea" class="col-lg-2 control-label">Descripción</label>
            <div class="col-lg-10">
                <%= f.text_area :description,
                placeholder: "Descripción del evento",
                id: "textArea",
                class: "form-control" %>
            </div>

        </div>
        <div class="form-group">
            <label for="inputStart" class="col-lg-2 control-label">Comienza</label>
            <div class="col-lg-10">
                <%= f.datetime_local_field :start_date,
                :value => Time.now,
                id: "inputStart",
                class: "form-control" %>
            </div>
            <label for="inputEnd" class="col-lg-2 control-label">Termina</label>
            <div class="col-lg-10">
                <%= f.datetime_local_field :end_date,
                placeholder: "yy-mm-dd, hh:mm",
                id: "inputEnd",
                class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <%= link_to "Cancelar", events_path, class: "btn btn-default" %>
                <%= f.submit "Guardar", class: "btn btn-primary" %>
            </div>
        </div>
    </fieldset>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<h5>Descripción:</h5>
<p class="lead">
    <%= @event.description %>
</p>

<!-- <h6>Lugar:</h6>
<p class="lead">
    <%= @event.place %>
</p> -->

<table class="table">
    <thead>
        <tr>
            <th><h6>Lugar</h6></th>
            <th><h6>Empieza</h6></th>
            <th><h6>Acaba</h6><th>
        </tr>
    </thead>
    <tr>
        <td><%= @event.place %></td>
        <td><%= @event.start_date %></td>
        <td><%= @event.end_date %></td>
    </tr>
</table>

<%= link_to 'Todos los eventos', events_path, class: "btn btn-default" %>
<%= link_to "Eliminar", @event,
    method: :delete,
    data: {confirm: 'Estas seguro?'},
    class: "btn btn-danger" %>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uniagenda</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/paper/bootstrap.min.css" rel="stylesheet"
  integrity="sha256-hMIwZV8FylgKjXnmRI2YY0HLnozYr7Cuo1JvRtzmPWs= sha512-k+wW4K+gHODPy/0gaAMUNmCItIunOZ+PeLW7iZwkDZH/wMaTrSJTt7zK6TGy6p+rnDBghAxdvu1LX2Ohg0ypDw==" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand" href="#">Uniagenda</a> -->
          <%= link_to 'Uniagenda', events_path, class: "navbar-brand" %>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete%></li>
            <% else %>
            <li><%= link_to "Iniciar sesión", new_user_session_path %></li>
            <li><%= link_to "Crear cuenta", new_user_registration_path%></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    </header>
    <!-- <p class="notice"><%= notice %></p> -->
    <!-- <p class="alert"><%= alert %></p> -->
    <div class="main-content">
        <%= yield %>

    </div>
</body>
</html>